/* eslint-disable max-lines */
import { StyleSheet } from 'react-native';
import { EdgeInsets } from 'react-native-safe-area-context';
import { ThemeColors } from '../../../core/theme/colors';
import { scale, verticalScale, scaleFont } from '../../../core/theme/responsive';

export const stylesFactory = (colors: ThemeColors, insets?: EdgeInsets) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    scrollContent: {
      paddingHorizontal: scale(20),
      paddingTop: verticalScale(16),
      paddingBottom: insets ? insets.bottom + verticalScale(24) : verticalScale(32),
    },
    // 1. Editorial Welcome & Profile Header Styles
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: verticalScale(26),
    },
    welcomeTitle: {
      fontSize: scaleFont(22),
      fontWeight: '700',
      color: colors.text,
      lineHeight: scaleFont(28),
      letterSpacing: -0.3,
    },
    welcomeSubtitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: verticalScale(3),
    },
    welcomeSubtitle: {
      color: colors.text + '80',
      fontSize: scaleFont(13),
      marginLeft: scale(4),
      fontWeight: '400',
    },
    avatarCircle: {
      width: scale(48),
      height: scale(48),
      borderRadius: scale(24),
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.03,
      shadowRadius: 6,
      elevation: 1,
    },
    // 2. Prestige Dual-Action Tiles Styles
    dualActionContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      marginBottom: verticalScale(28),
    },
    tileLeft: {
      width: '48%',
      height: verticalScale(170),
      backgroundColor: colors.primary === '#F8FAFC' ? '#18181B' : '#0F172A',
      borderRadius: scale(20),
      padding: scale(16),
      justifyContent: 'space-between',
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: scale(4) },
      shadowOpacity: 0.05,
      shadowRadius: scale(8),
      elevation: 3,
    },
    tileRight: {
      width: '48%',
      height: verticalScale(185),
      backgroundColor: colors.surface,
      borderRadius: scale(20),
      padding: scale(16),
      justifyContent: 'space-between',
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: scale(4) },
      shadowOpacity: 0.02,
      shadowRadius: scale(8),
      elevation: 2,
    },
    tileTitleLight: {
      color: '#FFFFFF',
      fontSize: scaleFont(17),
      fontWeight: '700',
      lineHeight: scaleFont(22),
      letterSpacing: -0.2,
    },
    tileTitleDark: {
      color: colors.text,
      fontSize: scaleFont(17),
      fontWeight: '700',
      lineHeight: scaleFont(22),
      letterSpacing: -0.2,
    },
    tileSubtitleLight: {
      color: 'rgba(255, 255, 255, 0.7)',
      fontSize: scaleFont(12),
      lineHeight: scaleFont(16),
    },
    tileSubtitleDark: {
      color: colors.text + '80',
      fontSize: scaleFont(12),
      lineHeight: scaleFont(16),
    },
    tileIconContainerLight: {
      width: scale(36),
      height: scale(36),
      borderRadius: scale(18),
      backgroundColor: 'rgba(255, 255, 255, 0.15)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    tileIconContainerDark: {
      width: scale(36),
      height: scale(36),
      borderRadius: scale(18),
      backgroundColor:
        colors.primary === '#F8FAFC' ? 'rgba(255, 255, 255, 0.08)' : 'rgba(15, 23, 42, 0.04)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    // 3. Curated Looks Carousel Banners Styles
    carouselContainer: {
      marginBottom: verticalScale(28),
    },
    carouselCard: {
      width: scale(250),
      height: verticalScale(140),
      borderRadius: scale(20),
      marginRight: scale(16),
      padding: scale(16),
      justifyContent: 'flex-end',
      overflow: 'hidden',
      position: 'relative',
    },
    carouselCardOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(15, 23, 42, 0.45)',
    },
    carouselPill: {
      backgroundColor: 'rgba(255, 255, 255, 0.2)',
      paddingHorizontal: scale(8),
      paddingVertical: scale(2),
      borderRadius: scale(10),
      alignSelf: 'flex-start',
      marginBottom: scale(6),
    },
    carouselPillText: {
      color: '#FFFFFF',
      fontSize: scaleFont(9),
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    carouselTitle: {
      color: '#FFFFFF',
      fontSize: scaleFont(15),
      fontWeight: '700',
      lineHeight: scaleFont(20),
    },
    // 4. Recent Activity/Secure Transactions Styles
    sectionHeaderRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: verticalScale(16),
    },
    sectionHeaderTitle: {
      fontSize: scaleFont(17),
      fontWeight: '700',
      color: colors.text,
      letterSpacing: -0.2,
    },
    seeAllButton: {
      paddingVertical: scale(4),
      paddingHorizontal: scale(6),
    },
    seeAllText: {
      fontSize: scaleFont(13),
      fontWeight: '600',
      color: colors.primary,
    },
    transactionList: {
      marginBottom: verticalScale(24),
    },
    transactionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: verticalScale(12),
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    transactionPlaceholder: {
      width: scale(44),
      height: scale(44),
      borderRadius: scale(10),
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: scale(12),
    },
    transactionInfo: {
      flex: 1,
    },
    transactionId: {
      fontSize: scaleFont(14),
      fontWeight: '600',
      color: colors.text,
    },
    transactionDate: {
      fontSize: scaleFont(11),
      color: colors.text + '80',
      marginTop: verticalScale(2),
    },
    transactionAmount: {
      fontSize: scaleFont(14),
      fontWeight: '700',
      color: colors.text,
    },
    // 5. Connectivity Diagnostics Card Styles
    networkWidget: {
      backgroundColor: colors.surface,
      borderRadius: scale(16),
      padding: scale(16),
      borderWidth: 1,
      borderColor: colors.border,
      marginTop: verticalScale(8),
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: scale(2) },
      shadowOpacity: 0.01,
      shadowRadius: scale(6),
      elevation: 1,
    },
    networkHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: verticalScale(6),
    },
    networkTitle: {
      marginLeft: scale(8),
      fontSize: scaleFont(14),
      fontWeight: '600',
      color: colors.text,
    },
    networkDesc: {
      color: colors.text + '70',
      marginBottom: verticalScale(12),
      lineHeight: verticalScale(16),
      fontSize: scaleFont(12),
    },
    networkBtn: {
      height: verticalScale(40),
      borderRadius: scale(10),
    },
    // Navigation bar icons
    headerCartButton: {
      marginRight: scale(16),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      padding: scale(4),
    },
    badgeContainer: {
      position: 'absolute',
      right: scale(-4),
      top: scale(-4),
      backgroundColor: colors.error,
      borderRadius: scale(8),
      minWidth: scale(16),
      height: scale(16),
      paddingHorizontal: scale(4),
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1.5,
      borderColor: colors.background,
    },
    badgeText: {
      color: '#FFFFFF',
      fontSize: scaleFont(9),
      fontWeight: '700',
      lineHeight: scaleFont(11),
      textAlign: 'center',
    },
  });
